language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt
  - pip install ".[test]" . 
  - pip install pytest-travis-fold
script: pytest 
after_success:
  - codecov
